name: paging_plus
version: 2.0.0

description: Lightweight pagination package. Calculate pages, determine next page to fetch, and handle load-more with optimized data fetching for Flutter & Dart.

repository: https://github.com/hossameldinmi/paging_plus

topics:
  - page
  - paging
  - pagination
  - infinite-scroll
  - load-more

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
